
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: MYTABLE
      description: "A starter dbt model"
      columns:
          - name: AMOUNT
            description: "The primary key for this table"
            tests:

    - name: Employee
      description: "Testing"
      columns:
          - name: EMPID
            description: "Testing"
            tests:
                 - unique
                
   
   
