
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: Employee
                
    - name: CustomerData
      description: "Table to Table load"
      columns:
          - name: CustID
            tests:
                 - unique
          - name: FirstName
          - name: LastName
          - name: Address
          - name: City      
             
    - name: Customer_Records 

    - name: TableCreationDemo
